### ISSUE TITLE
🎁 [Feature Request]: Allow users to specify installation location on `init`

### ISSUE THREAD

**Issue by ImmaZoni** [subspace/subspace-cli#122]
### What is the feature you would like to see?

It would be nice to ask the user where the would like to install the configuration files for the application, while our default locations are good and we should keep them some users may want to store these files on other drives etc. 

This was feedback from a community member during a testing phase

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ozgunozerk** [comment]
The app needs to know the location of the config file. If we want to grant the flexibility for moving the config file, than we would need another config file which is static, to tell the location of the other config file. 
I don't think this is something that is making things easier for the user. Config files are meant to be in a place, there are specific folders dedicated for them in each OS just because of this. 

Because of the above, I'm still inclined towards keeping it as is. 

If you have additional ideas, we can always discuss

**Comment by ozgunozerk** [comment]
@ImmaZoni going to close this if you don't have additional thoughts?
