### ISSUE TITLE
Initialization does not create parent directories

### ISSUE THREAD

**Issue by SilversterSunset** [subspace/subspace-cli#82]
Initialization does not create parent directories and the error is simply ignored. This behavior has already caused some problems. See https://discord.com/channels/864285291518361610/1050203487469850694.
https://github.com/subspace/subspace-cli/blob/e651ddf2ca3aa5881c3667daa67811818b94539f/src/config.rs#L147

**Comment by SilversterSunset** [comment]
As an alternative to creating parent directories, I can suggest creating a `~/.config` directory for Linux and implement error handling.

**Comment by ozgunozerk** [comment]
Thank you very much for the bug report, will inspect. 
There is a `create_dir_all` function that will handle this issue I believe. Let me inspect the issue first :) 
This should be a fast fix :)

**Comment by SilversterSunset** [comment]
If the person does not have permission to create the directory, then this can cause confusion later, as the error will indicate that the directory does not exist.

**Comment by ozgunozerk** [comment]
I couldn't reach the discord link you gave. But to my understanding, here is the issue:
due to no `.config/` directory present in user's root dir, the program is unable to create the subdirectory as well. Because the code assumes that `.config` directory would be present. 

In this case, `create_dir_all` will create all the required directories (including the missing `.config` dir for this example).

> If the person does not have permission to create the directory, then this can cause confusion later
This program (subspace-cli) will be run with user's privileges as well. If the current user that runs this program does not have the privileges to create folders, then this program will crash for sure. And I think it should be that way. This program includes heavy I/O operations, a user that doesn't have the privilege to create a directory in their root directory should not run this program in the first place imho.

**Comment by nazar-pc** [comment]
> In this case, create_dir_all will create all the required directories (including the missing .config dir for this example).

It will, the challenge is, however, it will not necessarily create it with necessary permissions and in some cases due to typo in path it may create unnecessary directories. So I'd personally prefer it to print an error explaining that path it is looking to create a subdirectory in doesn't exist. It should be enough information for user to work with and fix.

**Comment by ozgunozerk** [comment]
What about this?
```rust
    if let Err(err) = create_dir_all(&config_path) {
        // ignore the `AlreadyExists` error
        if err.kind() != io::ErrorKind::AlreadyExists {
            return Err(eyre!("could not create the directory, because: {err}"));
        }
    }
```

**Comment by nazar-pc** [comment]
That would be my preference for sure, but that is just me
